import json
import random
import uuid
from datetime import datetime
from typing import List, Dict, Optional

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field

from .config import Config, Persona

# حمل المتغيرات من ملف .env
load_dotenv()
client = OpenAI()


class QualityScores(BaseModel):
    vocab_diversity: Optional[float] = None
    semantic_novelty: Optional[float] = None
    domain_realism: Optional[float] = None
    bias_flags: List[str] = Field(default_factory=list)
    is_accepted: Optional[bool] = None


class Review(BaseModel):
    review_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    persona_id: str
    product: str
    rating: int
    title: str
    body: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    source_model: str = "stub"
    quality: QualityScores = Field(default_factory=QualityScores)


def _sample_rating(rating_distribution: Dict[int, float]) -> int:
    """اختر rating عشوائيًا طبقًا للتوزيع الموجود في الـ config."""
    ratings, probs = zip(*sorted(rating_distribution.items()))
    return random.choices(ratings, weights=probs, k=1)[0]


def _sample_persona(cfg: Config) -> Persona:
    return random.choice(cfg.personas)


# ---------- STUB GENERATION ----------

def generate_review_stub(cfg: Config, source_model: str = "stub") -> Review:
    """
    مولّد مبدئي (بدون LLM) عشان نختبر البايبلاين.
    لاحقًا هنستبدله بنداء للموديل.
    """
    persona = _sample_persona(cfg)
    product = random.choice(cfg.products)
    rating = _sample_rating(cfg.rating_distribution)

    title = f"Stub review for {product} ({rating}★)"
    body = (
        f"This is a placeholder review written by persona '{persona.id}' "
        f"about {product} with rating {rating}. "
        "Later this text will be generated by an LLM."
    )

    return Review(
        persona_id=persona.id,
        product=product,
        rating=rating,
        title=title,
        body=body,
        source_model=source_model,
    )


def generate_many_stub(cfg: Config, n: int) -> List[Review]:
    return [generate_review_stub(cfg) for _ in range(n)]


# ---------- OPENAI GENERATION ----------

def _build_prompt(persona: Persona, product: str, rating: int) -> str:
    # خلي بالك من الـ {{ و }} عشان f-string ما يعتبرهاش format
    return f"""
You are generating a realistic user review for a dev tool.

Persona:
- Role: {persona.role}
- Tone: {persona.tone}

Product: {product}
Rating: {rating} / 5

Requirements:
- Mention at least one concrete use case or workflow (e.g. debugging APIs, running tests in CI).
- Be consistent with the rating (low rating → more negatives, high rating → more positives).
- Length: 60–120 words.
- Avoid generic marketing buzzwords like "revolutionary" unless they sound natural.

Output ONLY valid JSON with this exact schema:
{{
  "title": "...",
  "body": "..."
}}
""".strip()


def generate_review_openai(cfg: Config, model: str = "gpt-4.1-mini") -> Review:
    persona = _sample_persona(cfg)
    product = random.choice(cfg.products)
    rating = _sample_rating(cfg.rating_distribution)

    prompt = _build_prompt(persona, product, rating)

    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "You generate realistic SaaS/dev-tools product reviews as structured JSON.",
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.9,
    )

    content = response.choices[0].message.content

    # مكتبة openai الجديدة أحيانًا ترجع list من القطع
    if isinstance(content, list):
        # لو رجعت structured parts
        text_parts = []
        for part in content:
            if hasattr(part, "text") and part.text is not None:
                text_parts.append(part.text)
        content = "".join(text_parts)

    if not isinstance(content, str):
        content = str(content)

    try:
        data = json.loads(content)
        title = data.get("title", f"Review for {product}")
        body = data.get("body", content)
    except json.JSONDecodeError:
        # fallback: نحط النص كله في body
        title = f"Review for {product}"
        body = content

    return Review(
        persona_id=persona.id,
        product=product,
        rating=rating,
        title=title,
        body=body,
        source_model=f"openai:{model}",
    )


def generate_many_openai(cfg: Config, n: int, model: str = "gpt-4.1-mini") -> List[Review]:
    return [generate_review_openai(cfg, model=model) for _ in range(n)]
